### ISSUE TITLE
quickstart fails to compile with Yamcs 5.6.0

### ISSUE THREAD

**Issue by merose** [yamcs/quickstart#8]
Yamcs 5.6 has removed the ByteArrayUtils.encodeShort() method. This is used by the sample command postprocessor in the quickstart project. Perhaps change to use `b[i] = value >> 8` and `b[i+1] = value & 0xFF`. (I also found that utility convenient. It may be good to add it back.)

~~~
...
[INFO] Compiling 2 source files to /Users/merose/git/quickstart/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/merose/git/quickstart/src/main/java/com/example/myproject/MyCommandPostprocessor.java:[57,23] cannot find symbol
  symbol:   method encodeShort(int,byte[],int)
  location: class org.yamcs.utils.ByteArrayUtils
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.469 s
[INFO] Finished at: 2022-03-17T11:09:18-07:00
[INFO] ------------------------------------------------------------------------
~~~

**Comment by merose** [comment]
Sorry, my mistake. I was using a fork and hadn't updated from the yamcs project. Will close this.
